terra-money/terra.js

package-lock.json, src/key/Key.ts, src/key/MnemonicKey.ts, src/key/RawKey.ts
To allow for async signing, for example over a network, the signing
function is changed to return a promise
=> Change signing interface to return promise

package-lock.json, src/core/distribution/proposals/CommunityPoolSpendProposal.ts, src/core/gov/msgs/MsgDeposit.ts, src/core/gov/msgs/MsgSubmitProposal.ts, src/core/msgauth/Authorization.ts, src/core/wasm/msgs/MsgExecuteContract.ts, src/core/wasm/msgs/MsgInstantiateContract.ts
This make it convenient to do the following:
```ts
new MsgInstantiateContract(
'terra...',
3,
{ init: msg },
{ ukrw: 1, uluna: 3},
false
)
```
Instead of:
```ts
new MsgInstantiateContract(
'terra...',
3,
{ init: msg },
new Coins({ ukrw: 1, uluna: 3 }),
false
)
```
for various classes. The classes changed are:
- CommunityPoolSpendProposal
- MsgInstantiateContract
- MsgExecuteContract
- SendAuthorization
- MsgDeposit
- MsgSubmitProposal
All other core data classes that are expected to be used by end-users already use this convenition, such as MsgSend and MsgMultiSend.
=> Change contstructors to use Coins.Input instead of Coins

package-lock.json, package.json, src/client/lcd/Wallet.ts
In order to change fee estimation parameters, one had to modify the `LCDClient` that generated the `Wallet` instance:
```ts
const terra = new LCDClient(...);
const mk = new MnemonicKey(...);
const wallet = terra.wallet(mk);
terra.config.gasPrices = ...
terra.config.gasAdjustment = ...
const unsignedTx = await wallet.createTx({
msgs: [send, swap], 
});
```
This pull requests makes it possible to specify the gas prices and gas adjustment without altering the global LCD configuration for a single instance of fee estimation via `Wallet.createTx`, (which is automatically reflected in `Wallet.createAndSignTx` as well). The optional fields `gasPrices` and `gasAdjustment` can be passed to `createTx` to override the defaults for the `LCDClient`'s fee estimation parameters.
```ts
const terra = new …
```
=> Feature: Change fee estimation parameters in Wallet.createTx

package-lock.json, package.json, src/client/lcd/Wallet.ts, src/client/lcd/api/TendermintAPI.ts, src/client/lcd/api/TxAPI.ts, src/core/TxInfo.ts, src/util/hash.ts
New function `TxAPI.txInfosByHeight` gives a list of transaction info by block height. 
`TendermintAPI.block(height)` was renamed to `TendermintAPI.blockInfo(height)` to maintain naming consistency with what was being returned. (cf. TxAPI.txInfo)
`TxInfo` was also missing the `code` field as @mesyakim pointed out. This allows for easy checking of a past transaction's failure on the chain.
=> Fix: Add 'txInfosByHeight' and 'code' to TxInfo

package-lock.json, package.json, src/extension/index.ts, src/index.ts, webpack.config.js
Exports `Extension` class for communicating between web browser context and Station Extension. The module has been implemented as singleton pattern thus multiple instantiation will return same instance.
Only browser can instantiate use class. Creating instance in Node.js will raise `Uncaught ReferenceError: window is not defined`
```javascript
import { Extension } from '@terra-money/terra.js'
const ext = new Extension()
// Send payload to Station Extension
ext.send({ action: "connectWallet" })
// Listen on WALLET message   
ext.on('WALLET', (payload) => {
})
```
=> Feature: Extension module

package-lock.json, package.json, src/extension/index.ts, src/key/Key.ts, src/key/MnemonicKey.ts, src/key/RawKey.ts
This PR adds feature to get recovery id produced from secp256k1.ecdsaSign function. To verify signature in EVM, recovery id and public key should be accessible.
* Add ecdsaSign method to MnemonicKey and RawKey which will passed to secp256k1.ecdsaSign to get signature and recid
```typescript
public ecdsaSign(
payload: Buffer
): { signature: Uint8Array; recid: number };
```
=> Support for signature and recovery id from ecdsaSign

package.json, src/client/lcd/api/TxAPI.ts, src/client/lcd/api/WasmAPI.ts, src/core/TxInfo.spec.ts, src/core/TxInfo.ts, src/core/params/proposals/ParameterChangeProposal.spec.ts, src/core/wasm/params.ts
- **BREAKING**: Event Parsing in `TxLog` and `BlockBroadcastResult`
- Update `TxInfo` and `TxLog` interfaces to Columbus-4
- Add `TxAPI.search`
--
The main breaking change is modifying `TxInfo.events` type signature from `Event[]` to `Events`. `Events` holds a parsed version of the blockchain events in a nested object instead of an inconvenient array.
To illustrate:
Before:
```ts
...
const storeCodeTxResult = await terra.tx.broadcast(tx);
const codeId = +storeCodeTxResult.logs[0].events[1].attributes[1].value;
```
After:
```ts
const storeCodeTxResult = await terra.tx.broadcast(tx);
const {
store_code: { code_id }
} = storeCodeTxResult.logs[0].events;
const codeId = +code_id[0];
```
You are no longer burdened with having to know which order the event comes in, and you can specify the event …
=> Feature: Add Event Parsing

package-lock.json, package.json, src/core/TxInfo.spec.ts, src/core/TxInfo.ts
In JSON tx results, `logs.events` is array of objects, and replacing variable `events` to object of arrays confuses developers.
* expose events as an array which is previous behavior.
* expose eventsByType
=> Fix: TxInfo.logs.events should be array

integration-tests/contract.ts, package.json, src/client/lcd/api/TxAPI.ts
If you are using typescript, you can import `isTxError()` function as a typeguard, which enforces good practice of checking that the returned result did not encounter an error.
Example from `contract.ts` integration test:
```ts
const storeCode = new MsgStoreCode(
wallet.key.accAddress,
fs.readFileSync('contract.wasm').toString('base64')
);
const storeCodeTx = await wallet.createAndSignTx({
msgs: [storeCode],
});
const storeCodeTxResult = await terra.tx.broadcast(storeCodeTx);
console.log(storeCodeTxResult);
if (isTxError(storeCodeTxResult)) {
throw new Error(
`store code failed. code: ${storeCodeTxResult.code}, codespace: ${storeCodeTxResult.codespace}, raw_log: ${storeCodeTxResult.raw_log}`
);
}
const {
store_code: { code_id },
} = storeCodeTxResult.logs[0].eventsByType;
```
Without the …
=> Add typeguard for TxBroadcastResult

package-lock.json, package.json, src/extension/index.ts
This PR adds waitForConfirmation and purgeQueue option to sign and post methods in extension module
* waitForConfirmation(default: false): extension will respond when transaction has been committed to the block
* purgeQueue(default: true): extension will purge other transaction requests which means if a developer set this variable as true, all tx requests will be queued and requested to users to make consecutive transactions.
=> Feature: add waitForConfirmation and purgeQueue option

package-lock.json, package.json, src/core/wasm/msgs/MsgExecuteContract.ts, src/core/wasm/msgs/MsgInstantiateContract.ts
Changes `MsgInstantiateContract` and `MsgExecuteContract` arguments for `coins` and `migratable` optional.
=> Make wasm msg arguments optional

package-lock.json, package.json, src/client/WebSocketClient.ts
This PR adds feature that allows WebSocketClient to be reconnected after the disconnect.
* added destroy method to WebSocketClient
* removed socket parameter from callback
* changed constructor signature
* WebSocketClient extends EventEmitter
**error** emitted when error raises
**connect** emitted after connection establishment
**reconnect** emitted upon every attempt of reconnection
**destroyed** emitted when socket has been destroyed
=> feat(client): added reconnect feature to WebSocketClient

integration-tests/clikey.ts, integration-tests/websocket.ts, package-lock.json, package.json, src/key/CLIKey.spec.ts, src/key/CLIKey.ts, src/key/Key.ts, src/key/MnemonicKey.spec.ts, src/key/MnemonicKey.ts, src/key/index.ts, webpack.config.js, yarn.lock
`CLIKey` is available on Node.js runtimes and allows Terra.js to use keys stored and registered with `terracli`. This implementation assumes the latest version of `terracli` has been installed and is available in the user's path. The solution also works with keys registered with `terracli` that use Ledger.
Usage:
```ts
import { StdFee, MsgSend } from '../src';
import { LocalTerra } from '../src';
import { CLIKey } from '../src';
const terra = new LocalTerra();
const { test1 } = terra.wallets;
const cliKey = new CLIKey('<key-name>');
const cliWallet = terra.wallet(cliKey);
const send = new MsgSend(cliWallet.key.accAddress, test1.key.accAddress, { uluna: 100000 });
async function main() {
const tx = await cliWallet.createAndSignTx({
msgs: [send],
fee: new StdFee(100000, { uluna: 100000 }) …
```
=> Feature: CLIKey

integration-tests/clikey.ts, package-lock.json, package.json, src/extension/index.ts, src/key/index.ts, webpack.config.js
Version will be updated to 1.0.0 to follow https://semver.org/ standard.
IgnorePlugin cannot ignore source code line for importing CLIKey which leads browser to raise an exception. To fix this problem, CLIKey was removed from `index`. Developer have to explicitly import CLIKey from now on.
Extension.isAvailable was using `window.Terra.isAvailable` variable to determine whether there's Terra Station Extension installed or not, assigned by Terra Station Extension.
However, there will be a conflict on `window.Terra` when terra.js is included by using <script> tag
=> Fix CLIKey and Extension.isAvailable

package-lock.json, package.json, src/client/lcd/api/OracleAPI.ts, src/core/Coins.ts
In `LCDClient`:
Sometimes, the result from `OracleAPI.exchangeRate(denom)` will complain because the result from `OracleAPI.exchangeRates()` is `undefined`. The intended behavior is `OracleAPI.exchangeRate(denom)` should be `undefined` when not found -- OracleAPI.exchangeRates() should be empty `Coins` object.
=> Fix: Oracle Null Check

src/client/lcd/api/TreasuryAPI.ts
I noticed that the LCD api supports a providing height for the taxRate API node. 
This feature exists in the FCD implementation of the LCD client, so I ported it over to the LCD client in terra.js
https://github.com/terra-project/fcd/blob/develop/src/lib/lcd.ts
=> Added support for height parameter in the taxRate LCD api

src/client/lcd/api/StakingAPI.ts
The API states parameters are options for either delegator or validator, but implementation currently requires both.
=> Allow optional parameters for lcd.staking.unbondingDelegations

package-lock.json, package.json, src/core/staking/Validator.spec.ts, src/core/wasm/msgs/MsgExecuteContract.spec.ts, src/util/contract.ts
Some Msg types have `fromData` function that provide the convenience of parsing Base64-encoded JSON strings into objects, such as `MsgExecuteContract`. However, it is not always the case these strings are proper; the node does not check that the argument to `execute_msg` be a valid JSON string.
Example: https://fcd.terra.dev/txs/8AFFBC576725244C405E48A5FEE3DF35D6934DBC779C6C17604985C88C82B496
This hotfix will just skip the parsing if it runs into an error (base-64 or JSON decoding) and keep the raw string.
=> Fix JSON Parsing Error when WASM messages aren't proper JSON

src/client/lcd/api/WasmAPI.ts
When using localterra with the bombay branch, I can no longer call `contractInfo()` successfully. It looks like the `init_msg` in the result is no longer a base64 JSON string.
=> Fix contractInfo result parsing

.github/workflows/main.yml, .github/workflows/typedoc.yml, package-lock.json, package.json
There were two issues with the GitHub Action workflows:
1. npm dependencies were not being properly cached in the CI workflow
2. The TypeDoc workflow was failing, causing GitHub Pages to not be updated
This was because:
- `yarn` was removed in favor of `npm` in 7bcbd6096366b47502507e27e1b57721500bb515, but the workflows were never updated.
- In the CI workflow, `yarn.lock` was still being used as the node_modules cache key
- In the TypeDoc workflow, the `yarn` commands were still being used
- Since there was no `yarn.lock`, `yarn` would install the latest versions of all dependencies permitted in `package.json`, including `typescript 4.3`, which TypeDoc does not yet support. This ultimately caused that workflow to fail.
This PR:
1. Updates the CI workflow to use `package-lock.json` as the …
=> Fix GitHub Action Workflows

integration-tests/estimateFee.ts, package-lock.json, package.json, src/client/lcd/LCDClient.ts
There is a weird bug in core that estimate fee returns too low gas depending on the address you put for MsgSend which leads terra.js to create failed tx caused by `out of gas` error. To fix this problem, this PR increases gas adjustment to 1.75 which was proven by several dApps
=> Increase default gas adjustment

README.md
To use react native, react-native-get-random-values package must be included along with node-libs-react-native.
Without adding it, an error occurs.
```
ERROR    Error: Crypto module not found
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```
=> Add description of react native configuration

src/client/lcd/api/TxAPI.ts
I was working on integrating ZenGo wallet for Terra Bombay testnet and noticed an issue when trying to estimate the fee of a transaction.
The problem occurs when trying to call the `estimateFee` function such that the intersection of the denom coins of the `gasPrice` parameter and the `feeDenoms` parameter are an empty set. The `filter` applied to the `gasPricesCoins` variable leaves it as an empty set of `Coins` which causes the resulting estimated fee to ignore the gas portion of the fee, resulting in 
an `insufficient fee` error when trying to send a tx based on the resulting (erroneous) fees.
--------------------------------------------------------------------------
**Commit message**
The existing issue with the estimateFee function is that the
'gasPricesCoins' variable can end up …
=> Handle mismatching coins in estimateFee gasPrices and feeDenoms

package-lock.json, package.json, src/client/lcd/APIRequester.ts, src/client/lcd/LCDClient.ts, src/client/lcd/api/WasmAPI.ts, src/util/contract.ts
* When constructing LCDClient, it will call a function for enable/disabling  base64 encoding for wasm messages. (e.g. init_msg, execute_msg and migrate_msg) depending on the chain id provided. For Bombay/Columbus-5, it will disable the encoding.
* Default 30 seconds timeout for Axios to avoid deadlock situtation.
=> Wasm message compatibility for Bombay/Columbus-5

package-lock.json, package.json, src/core/wasm/msgs/MsgExecuteContract.ts, src/core/wasm/msgs/MsgInstantiateContract.ts, src/core/wasm/msgs/MsgMigrateContract.ts, src/util/json.spec.ts, src/util/json.ts
close #119 
After the core changed its wasm msg type to json.RawMessage, it automatically remove null properties at decoding. To prevent verification error, js also need to remove null properties at building sign data.
also replace empty string admin to undefined at wasm.instantiate
=> [Feature] Remove null property from wasm execute msg

src/core/Coins.spec.ts, src/core/Coins.ts
Adding `Iterable` interface to `Coins` construct. 
- This is useful when `Coins` need to be serialized into `Coin[]` by default javascript behaviours (i.e. tossing around in GraphQL resolver chains).
- Makes sense as the nominal type for `Coins` is `Coin[]` anyway, and object representation is optional.
- Does NOT affect any methods.
=> feat: add iterable interface to Coins

package-lock.json, package.json, src/core/StdSignature.ts
close #139 
I also read cosmos-sdk code, and it seems we can broadcast tx with empty pubkey when the signer pubkey is already known.
=> Pubkey can be null in tx info

.github/workflows/main.yml, package.json, src/client/lcd/api/AuthAPI.ts, src/core/Coin.spec.ts, src/core/auth/Account.spec.ts, src/core/auth/Account.ts, src/key/CLIKey.ts, src/util/json.ts
The file `src/key/CLIKey.ts` had a couple of prettier formatting issues in master so I added a task to run prettier in the CI to raise these on PRs. 
- Updated to run prettier in CI along with the linting
- Fixed any eslint warnings
- Updated prettier task name to `format` as a more common script name
=> Run prettier formatting in CI

integration-tests/websocket.ts, package-lock.json, package.json, src/client/WebSocketClient.ts, src/extension/index.ts
Extension module was using static "station:xx" as a stream name which makes every installed terra compatible wallets to respond.
Add an identifier parameter to Extension constructor and use it as a prefix of stream name, which will be decided by users (or frontend developers). Identifier must be unique to each wallet.
The default parameter for Extension constructor is "station" for backward compatibility
**Before**
new Extension()
**After**
new Extension('uniquququwallet')
=> Extension: add identifier for targeting a specific wallet extension

src/client/lcd/api/GovAPI.spec.ts, src/client/lcd/api/GovAPI.ts
Response from below endpoint says that the periods are `string` not `number`.
https://lcd.terra.dev/cosmos/gov/v1beta1/params/voting
https://lcd.terra.dev/cosmos/gov/v1beta1/params/deposit
=> fix: Types of paramters from GovAPI

src/client/lcd/api/GovAPI.spec.ts, src/client/lcd/api/GovAPI.ts
This reverts commit fbc4c9d9c26dfbf740b3a484e92f73468598a596.
terra.js already parses them to a `number` type
=> Revert "fix: Types of paramters from GovAPI"

integration-tests/decodeMsgVerifyInvariant.ts, src/core/Msg.ts, src/core/crisis/MsgVerifyInvariant.spec.ts, src/core/crisis/MsgVerifyInvariant.ts, src/core/crisis/index.ts
add crisis module and MsgVerifyInvariant
cc: @ALPAC-4 see [this example](https://github.com/terra-money/terra.js/compare/feature/crisis?expand=1#diff-9d00cfca87685675034d19308eec7f283d4200f3d6b17494982a1c1f98be5543)
=> add crisis/MsgVerifyInvariant

src/core/gov/Proposal.ts, src/core/ibc/proposals/ClientUpdateProposal.spec.ts, src/core/ibc/proposals/ClientUpdateProposal.ts, src/core/ibc/proposals/index.ts
We've had our first ClientUpdateProposal proposal: https://lcd.terra.dev/cosmos/gov/v1beta1/proposals/775
Terra.js is currently lacking support for parsing this proposal type which leads to the following situation: 
Preview of proposal details:
=> feat: Add ClientUpdateProposal type.

src/client/lcd/api/TxAPI.spec.ts, src/client/lcd/api/TxAPI.ts
We've received a lot of feedback that the default broadcast method can timeout before a transaction has been included in a block, even when the tx is included shortly after. In my testing this is due to broadcast attempting to keep the HTTP connection alive, and the connection can get closed by the client.
The official docs recommend against using broadcast block due to this exact issue: 
> It is important to note that the block mode should **not** be used in most circumstances. This is because broadcasting can timeout but the tx may still be included in a block. This can result in many undesirable situations. Therefore, it is best to use sync or async and query by tx hash to determine when the tx is included in a block.
source: https://hub.cosmos.network/main/resources/gaiad.html#tx-broad …
=> feat: Update broadcast to poll for the transaction

src/key/index.ts
Not sure if CLIKey is inaccessible on purpose i.e. unstable/still in-development but it seems to be the only semi-smooth way to share keys between terrad and terra.js as of now without exporting the `terrad` key from the keychain. 
A less frictionless but safe solution would be to document how to recreate the key from raw bytes in terra.js given that there is enough exportable information for a competent developer to bridge the gap:
```bash 
$terrad keys export terradev
-----BEGIN TENDERMINT PRIVATE KEY-----
salt: ED03DCECA6AA0C97C64777ADEC081118
type: secp256k1
kdf: bcrypt
bQeIuMrPqIOuQHfQw9otw5o2XnNcTmVK3yltvGUipjYpr0K8SfevG+/KRkB2F4eh
VpUUj0tHh434QYoJd69pJ9U8tesVkKCruyOsiHI=
=Jkvg
-----END TENDERMINT PRIVATE KEY-----
```
```bash
$terrad keys export terradev --unsafe --unarmored-hex …
```
=> fix(reimport): added `CLIKey` export to the module

src/core/params/proposals/ParameterChangeProposal.spec.ts, src/key/CLIKey.ts, src/key/index.ts
```typescript
import {CLIKey} from '@terra-money/terra.js'
const clikey = new CLIKey({
'keyName':'terradev',
})
console.log(clikey.accAddress);
console.log(clikey.valAddress);
```
Current implementation panics with (truncated, full error at the bottom if interested):
```
Error: Command failed: terrad keys show terradev --output json --home /home/rxz/go/bin/terrad
Error: couldn't get client config: Config File "client" Not Found in "[/home/rxz/go/bin/terrad/config]"
```
With changed path: 
```typescript
terra1hw4twm4kajhjpl6qapg0pn2cdtpnagp65planh
terravaloper1hw4twm4kajhjpl6qapg0pn2cdtpnagp65wnqry
```
...having changed default home to `$HOME/.terrad/config`, which seems to be the default for the last few versions of core did the trick.  $HOME is per node's`os`. 
```bash
Error: couldn't …
```
=> fix(clikey): changed default`terrad` home path

src/util/contract.ts
#262 breaks functions in src/util/contract.ts and intergration-tests/contract.ts
so updated utility functions to accept WaitTxBroadcastResult.
=> fix: make util/contract to support new broadcast()

src/client/lcd/APIRequester.spec.ts, src/client/lcd/APIRequester.ts
Hey there! 👋🏻 
This PR allows us to provide a special endpoint as LCD.
Currently, providing an endpoint with search parameters makes the whole thing break.
For example, if we were using `https://lcd.terra.dev?key=123` the endpoint would have been `https://lcd.terra.dev?key=123/foo/bar`.
Using the `URL()` API helps us to keep any search parameters in the URL.
=> fix(client:api-requester): allow special endpoint

src/client/lcd/api/WasmAPI.ts, src/core/wasm/AbsoluteTxPosition.ts, src/core/wasm/AccessConfig.ts, src/core/wasm/AccessTypeParam.ts, src/core/wasm/HistoryEntry.ts, src/core/wasm/util.ts
core v2 returns AccessType in form of human-friendly string like 'Everybody' by wasm/type/params.go
But accessTypeFromJSON requires "ACCESS_TYPE_EVERYBODY"
so wrapper function to get AccessType from human-friendly string added.
=> fix parsing code_info.instantiate_permission by adding converter

src/core/auth/ContinuousVestingAccount.spec.ts, src/core/auth/ContinuousVestingAccount.ts, src/core/auth/DelayedVestingAccount.spec.ts, src/core/auth/DelayedVestingAccount.ts, src/core/auth/PeriodicVestingAccount.spec.ts, src/core/auth/PeriodicVestingAccount.ts, src/core/ibc/applications/fee/msgs/MsgPayPacketFee.ts, src/core/ibc/applications/fee/msgs/MsgPayPacketFeeAsync.ts, src/core/ibc/applications/fee/msgs/MsgRegisterCounterpartAddress.ts
=> fix typo in error message

src/core/wasm/msgs/MsgClearContractAdmin.ts, src/core/wasm/msgs/MsgExecuteContract.spec.ts, src/core/wasm/msgs/MsgExecuteContract.ts, src/core/wasm/msgs/MsgInstantiateContract.spec.ts, src/core/wasm/msgs/MsgInstantiateContract.ts, src/core/wasm/msgs/MsgMigrateCode.ts, src/core/wasm/msgs/MsgMigrateContract.spec.ts, src/core/wasm/msgs/MsgMigrateContract.ts, src/core/wasm/msgs/MsgStoreCode.ts, src/core/wasm/msgs/MsgUpdateContractAdmin.ts
The so-called "parity upgrade" on Terra Classic is bringing the message format and type URLs of wasmd related messages to parity with Terra. This PR contains:
- Update of all smart contract related messages to ignore `isClassic` flag
- Retain `isClassic` flag for compatibility
- Tested manually with local script
- Remove legacy test case as deprecated
Note, that we did not include updates for the wasm related proposal types, because the governance facilities of wasmd will not be enabled during this upgrade. Please, review and consider to backport it to current release branch of terra.js, so it can be used in station mobile. Thank you.
=> Classic: Parity of WASM Messages

src/client/lcd/api/WasmAPI.ts, src/core/wasm/proposals/ClearAdminProposal.ts, src/core/wasm/proposals/ExecuteContractProposal.ts, src/core/wasm/proposals/InstantiateContractProposal.ts, src/core/wasm/proposals/MigrateContractProposal.ts, src/core/wasm/proposals/PinCodesProposal.ts, src/core/wasm/proposals/StoreCodeProposal.ts, src/core/wasm/proposals/SudoContractProposal.ts, src/core/wasm/proposals/UnpinCodesProposal.ts, src/core/wasm/proposals/UpdateAdminProposal.ts, src/core/wasm/proposals/UpdateInstantiateConfigProposal.ts
Dear @alecande11,
We politely ask you to review this PR and get it merged so that end-users can have flawless experience on station mobile. We figured the changes in #356 may have been too many to get quickly reviewed and merged. This is why we tried to condense it down to a bare minimum for you guys to be easier reviewable. We will close #356 in favor of this PR. Thank you so much for your ongoing support.
Changes:
- Support WASM related proposal types
- Support canonical WASM API for classic
Humbly,
Till
=> Feat: Support WASM Proposal Types and API (Minimal)
