terra-money/terra.js

package-lock.json, package.json, src/key/MnemonicKey.spec.ts, webpack.config.js
This will reduce the size of the bundle a little.
=> Include only bip39 english wordlists to bundle

README.md, package-lock.json, package.json, src/extension/index.ts, src/util/hash.ts
Support terra.js on React Native environment. [node-libs-react-native](https://github.com/parshap/node-libs-react-native) setup is required.
=> Support React Native

package-lock.json, package.json, src/extension/index.ts
Adds isAvailable getter to extension module for checking extension installation.
* Version 0.4.19
* Added `get isAvailable(): boolean` to Extension class
=> Add isAvailable getter to extension module

package-lock.json, package.json, src/core/Block.ts
This PR fixes updated typescript information for TendermintAPI BlockInfo
Fixes: #38
=> fix(core): apply columbus-4 BlockInfo

integration-tests/clikey.ts, package-lock.json, src/key/CLIKey.ts
Change CLIKey to use CLIKeyParams object as constructor parameter
=> fix(CLIKey): use object as params

package-lock.json, package.json, src/extension/index.ts
* Removed lcdClientConfig parameter from Option. Extension will **not** allow developers to specify this for security reasons.
* The response of connect has been changed: it was returning address as a string before, now it is returning object with address and network information.
* on(name, callback) and on(callback) is both available. If first argument is a callback, it will be triggered on every event
=> Extension Module Update

package-lock.json, package.json, src/core/Denom.ts, src/core/params/proposals/ParameterChangeProposal.spec.ts
* Version 1.3.7
* Added INR, CAD, CHF, AUD, SGD to Denom namespace
* Updated NPM modules
* Fix lint warning in test
=> New Stablecoins

README.md
Remove the deprecated testnet and chain and replace it for an active one
=> Update testnet in readme file

src/client/lcd/LCDClient.ts, src/client/lcd/LCDUtils.ts, src/client/lcd/Wallet.ts, src/client/lcd/api/MintAPI.spec.ts, src/core/Proposal.ts, src/core/auth/LazyGradedVestingAccount.spec.ts, src/core/distribution/params.ts, src/core/gov/params.ts, src/core/market/params.ts, src/core/oracle/AggregateExchangeRateVote.ts, src/core/oracle/msgs/MsgAggregateExchangeRatePrevote.ts, src/core/oracle/msgs/MsgExchangeRatePrevote.ts, src/core/oracle/params.ts, src/core/treasury/params.ts, src/core/wasm/params.ts, src/key/CLIKey.ts, src/key/Key.ts, src/key/MnemonicKey.spec.ts, src/key/RawKey.spec.ts, src/util/convert.ts
a housekeeping PR. No breaking or logical changes
=> refactor: reduce circular imports

src/client/lcd/LCDClient.ts, src/client/lcd/api/StakingAPI.spec.ts
Adding some more tests to StakingAPI module for clarifying changes in next mainnet
=> Add more tests to StakingAPI module

src/core/staking/Validator.ts, src/core/staking/msgs/MsgEditValidator.ts
Another preparation PR to reduce soure code changes in next mainnet
=> Preparation for omitted field in next mainnet

src/core/staking/msgs/MsgEditValidator.data.json, src/core/staking/msgs/MsgEditValidator.ts
Fix a hidden(no one tried) bug in MsgEditValidator
=> Fix MsgEditValidator bug

package-lock.json, package.json, src/client/lcd/api/TxAPI.ts
This PR has a fix for regular expression bug (but still working) for detecting columbus-5 compatibility in estimateFee function.
=> Fix minor regular expression bug

.github/workflows/npm-publish.yml
This PR adds npm publish automation for releases
=> Add npm publish automation

package-lock.json, package.json, src/core/wasm/msgs/MsgInstantiateContract.ts, src/core/wasm/msgs/MsgMigrateContract.ts
Terra.js 1.x is not designed to work with columbus-5/bombay. However, we've added #101 to 1.x to avoid making another Station extension in Chrome Web Store. This PR adds compatibility layer for MsgInstantiateContract and MsgMigrateContract.
=> Compatibility for MsgInstantiateContract and MsgMigrateContract

package-lock.json, package.json, src/client/lcd/api/GovAPI.ts
> This PR is for Columbus-4 (Terra.js 1.x)
Support `voter`, `depositor`, and `status`('deposit_period' | 'voting_period' | 'passed' | 'rejected') query parameter for LCD query {lcd}/gov/proposals
=> Support query parameters for {lcd}/gov/proposals 

package-lock.json, src/client/lcd/api/GovAPI.spec.ts, src/core/market/params.ts, src/core/params/ParamChange.ts
There were missing param changes in market module which causes an exception when querying governance proposals.
=> Add missing tobintax and minspread market param changes

integration-tests/send.ts, src/client/lcd/api/TxAPI.ts
[This](https://github.com/terra-money/core/pull/551) core update introduce additional features to `/txs` endpoints. 
It will allow users to use new feature like `fee_grant` and `timeout_height`, also it provides sequence number infos for legacy tx conversion.
=> [Feature] update `/txs` endpoint to receive additional inputs

src/key/CLIKey.ts
From @terra-money/core v0.5.0 do not support terracli anymore.
Change terracli to terrad.
=> fix: convert terracli to terrad

package-lock.json, package.json, src/core/gov/Proposal.ts, src/core/gov/Vote.ts, src/core/upgrade/Plan.spec.ts, src/core/upgrade/Plan.ts, src/core/upgrade/proposals/CancelSoftwareUpgradeProposal.spec.ts, src/core/upgrade/proposals/CancelSoftwareUpgradeProposal.ts, src/core/upgrade/proposals/SoftwareUpgradeProposal.spec.ts, src/core/upgrade/proposals/SoftwareUpgradeProposal.ts, src/core/upgrade/proposals/index.ts
This PR backports upgrade module support for governance proposal and also removes status and voting option mappings since it's not supported by protobuf
=> Backport upgrade module to 2.0.x

src/client/lcd/api/IbcTransferAPI.spec.ts, src/client/lcd/api/IbcTransferAPI.ts
fix return type of ...
- IbcTransferAPI.denomTrace()
- IbcTransferAPI.denomTraces()
=> fix query return format of denomTrace[s]

.github/workflows/main.yml, .github/workflows/npm-publish.yml, src/client/lcd/api/IbcTransferAPI.spec.ts
Github action is using outdated Node.js
=> Use Node.js v16 for github action

src/core/Dec.spec.ts, src/core/numeric.ts
=> remove prototype modification for decimal.js

src/client/lcd/LCDClient.ts, src/client/lcd/api/FeeGrantAPI.spec.ts, src/client/lcd/api/FeeGrantAPI.ts, src/client/lcd/api/index.ts
Add feegrant query that can get allowances.
=> feat: add fee grant query

package-lock.json, package.json, src/key/Key.ts, webpack.config.js
Fixes an exception bug in valAddress in Key class
Also fixes #123 Fix `process is not defined`
=> Fix key validator address

src/core/SignatureV2.spec.ts, src/core/SignatureV2.ts
=> add toData function for SignatureV2

src/client/lcd/api/TxAPI.ts
=> fix comments for broadcastSync/Async

integration-tests/contract_string.ts, src/client/lcd/api/WasmAPI.ts, src/core/wasm/msgs/MsgExecuteContract.ts
=> wasm query/execute accepts string params

src/core/crisis/MsgVerifyInvariant.spec.ts, src/core/crisis/MsgVerifyInvariant.ts
to prevent send the message to people's own node.
=> disallow to send MsgVerifyInvariant

integration-tests/paramchangeproposal.ts, package-lock.json, src/core/params/proposals/ParameterChangeProposal.spec.ts
When we launched Columbus-5, ParamChangeProposal tests were commented out due to conflicts from CosmosSDK. This PR brings both spec and integration tests back.
=> Fix tests for ParamChangeProposal

integration-tests/contract_string.ts
with newly instantiated contract
=> fix integration test: contract address for test with string-params

package-lock.json, package.json, src/client/lcd/api/TxAPI.ts, webpack.config.js
blockInfoByHeight in TxAPI creates tx query in a block by using Promise.all which creates the same number of api requests at once. This PR modifies this to make only one API request at a time.
=> Prevent tx query spamming

src/client/lcd/api/GovAPI.spec.ts, src/core/auth/BaseVestingAccount.ts
Minor changes
- support fromAmino for new-core
- fix code convention
=> support fromAmino for new-core in BaseVestingAccount

package-lock.json, package.json
=> bump terra.proto

src/client/lcd/api/TxAPI.ts
=> add slash to path

src/core/Msg.ts, src/core/distribution/msgs/MsgWithdrawValidatorCommission.spec.ts, src/core/distribution/msgs/MsgWithdrawValidatorCommission.ts
=> fix: type of withdraw validator commission message
